name: 'The Empire Builders Group'
email: 'info@empirebuilders.com'
phone: '1-800-599-0353'
address: '13 S. Letitia St, Philadelphia, PA 19106'
tagline: 'Data — Process — Technology: Aligned'

markdown: rdiscount
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile
pygments: true

url: http://theempirebuildersgroup.com
baseurl: http://theempirebuildersgroup.com
assets: /assets
relative_permalinks: false
permalink: pretty

prose:
    siteurl: 'http://okayjeffrey.github.io/ebg/'
    media: 'img'
